src_1 - 복사본/Project/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    re_path(r'^$', views.LoginView.as_view(), name="login_url"),

    #Index
    re_path(r'^$', views.IndexView.as_view(), name="index_url"),
    
    path('users/', include('users.urls', namespace="users")),
]

src_1 - 복사본/app/urls.py
from django.urls import re_path, path , include
from . import views

app_name = "users"


urlpatterns = [
   	# Login, Register, Forgot password, Logout
    re_path(r'^index/$', views.IndexView.as_view(), name="index_url"),
    re_path(r'^login/$', views.LoginView.as_view(), name="login_url"),
    re_path(r'^register/$', views.RegisterView.as_view(), name="register_url"),
    re_path(r'^forgot-password/$', views.ForgotPasswordView.as_view(), name="forgot_password_url"),
    re_path(r'^logout/$', views.LogoutView.as_view(), name="logout_url"),

    re_path(r'^charts/$', views.ChartsView.as_view(), name="charts_url"),


    re_path(r'^tables/$', views.TablesView.as_view(), name="tables_url"),
    re_path(r'^tables_result/$', views.Tables_result_View.as_view(), name="tables_result_url"),


    re_path(r'^tables1/$', views.TablesView1.as_view(), name="tables1_url"),
    re_path(r'^tables2/$', views.TablesView2.as_view(), name="tables2_url"),
    re_path(r'^tables3/$', views.TablesView3.as_view(), name="tables3_url"),
    re_path(r'^tables4/$', views.TablesView4.as_view(), name="tables4_url"),
    re_path(r'^tables5/$', views.TablesView5.as_view(), name="tables5_url"),
    re_path(r'^tables6/$', views.TablesView6.as_view(), name="tables6_url"),
    re_path(r'^tables7/$', views.TablesView7.as_view(), name="tables7_url"),
    re_path(r'^tables8/$', views.TablesView8.as_view(), name="tables8_url"),
    
    re_path(r'^simulation_count_url/$', views.simulation_count_url.as_view(), name="simulation_count_url"),
    re_path(r'^simulation_count_results_url/$', views.simulation_count_results_url.as_view(), name="simulation_count_results_url"),

    re_path(r'^simulation_close_url/$', views.simulation_close_url.as_view(), name="simulation_close_url"),
    re_path(r'^simulation_close_results_url/$', views.simulation_close_results_url.as_view(), name="simulation_close_results_url"),

    re_path(r'^buttons/$', views.ButtonsView.as_view(), name="buttons_url"),

    re_path(r'^cards/$', views.CardsView.as_view(), name="cards_url"),

	re_path(r'^page_not_found/$', views.PageNotFoundView.as_view(), name="page_not_found_url"),    

	re_path(r'^blank/$', views.BlankView.as_view(), name="blank_page_url"),    

	# Utilities
	re_path(r'^colors/$', views.ColorsView.as_view(), name="colors_url"),    

	re_path(r'^borders/$', views.BordersView.as_view(), name="borders_url"),    

	re_path(r'^animations/$', views.AnimationsView.as_view(), name="animations_url"),    

	re_path(r'^others/$', views.OthersView.as_view(), name="others_url"),    

    # re_path(r'^map/$', views.Map_View.as_view(), name="map_view_url"),
    # re_path(r'^tables1/$', views.Map_View1.as_view(), name="map_view1_url"),
    # re_path(r'^map/$', views.Map_View2.as_view(), name="index_url"),
    
]

src_1 - 복사본/ui/templates/theme/blank.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Blank {% endblock %}

{% block container_fluid %}
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

</div>
{% endblock %}

src_1 - 복사본/ui/templates/theme/charts.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Charts {% endblock %}

{% block container_fluid %}
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Charts</h1>
    <!-- <p class="mb-4">Chart.js is a third party plugin that is used to generate the charts in this theme. The charts below have been customized - for further customization options, please visit the <a target="_blank" href="https://www.chartjs.org/docs/latest/">official Chart.js documentation</a>.</p> -->
    <!-- Content Row -->
    <div class="row">
        <div class="col-xl-8 col-lg-7">
            <!-- Area Chart -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
                </div>
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="myAreaChart"></canvas>
                    </div>
                    <hr>
                    <!-- Styling for the area chart can be found in the <code>/js/demo/chart-area-demo.js</code> file. -->
                </div>
            </div>
            <!-- Bar Chart -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
                </div>
                <div class="card-body">
                    <div class="chart-bar">
                        <canvas id="myBarChart"></canvas>
                    </div>
                    <hr>
                    <!-- Styling for the bar chart can be found in the <code>/js/demo/chart-bar-demo.js</code> file. -->
                </div>
            </div>
        </div>
        <!-- Donut Chart -->
        <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4">
                        <canvas id="myPieChart"></canvas>
                    </div>
                    <hr>
                    <!-- Styling for the donut chart can be found in the <code>/js/demo/chart-pie-demo.js</code> file. -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_body %} 
    {% include 'theme/components/charts_scripts.html' %}
    <!-- Page level custom scripts (Only for charts page) -->
    <script src="{% static 'js/demo/chart-bar-demo.js' %}"></script>
{% endblock %}

src_1 - 복사본/ui/templates/theme/login.html
{% extends 'base_x.html' %}
{% load static %}

{% block title %} Login {% endblock %}

{% block container %}

<body class = "bg-login-image">
<div class="container ">
    <!-- Outer Row -->
    <div class="row justify-content-center ">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        
                        <div class="col-lg-6 d-none d-lg-block "></div>
                       
                            <div class="col-lg-8 offset-lg-2">
                                <div class="p-5">
                                    
                                    <div class="text-center">
                                        <img class="img-fluid transparency-grid" src="{% static 'resource/logos/title1.png' %}" ondragstart="return false;" data-hj-suppress="true" data-v-1ab68894="" style="max-width: 90%; height: auto;">
                                        <h1 class="h4 text-gray-900 mb-4"></h1>
                                        
                                    
                                    </div>
                                        <form class="user">
                                            <div class="form-group">
                                                <label for="email">ID</label>
                                                <input type="email" class="form-control form-control-user" id="email" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                                            </div>
                                            <div class="form-group">
                                                <label for="password">Password</label>
                                                <input type="password" class="form-control form-control-user" id="password" placeholder="Password">
                                            </div>
                                            <!-- <div class="form-group">
                                                <div class="custom-control custom-checkbox small">
                                                    <input type="checkbox" class="custom-control-input" id="customCheck">
                                                    <label class="custom-control-label" for="customCheck">Remember Me</label>
                                                </div>
                                            </div> -->
                                            <a href="{% url 'users:index_url' %}" class="btn btn-primary btn-user btn-block">
                                            Login
                                            </a>
                                            <!-- <hr>
                                            <a href="{% url 'index_url' %}" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i> Login with Google
                                            </a>
                                            <a href="{% url 'index_url' %}" class="btn btn-facebook btn-user btn-block">
                                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                            </a> -->
                                        </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'users:forgot_password_url' %}">
                                        비밀번호 찾기
                                        </a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'users:register_url' %}">  계정생성
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

{% block js_body %}
  <script type="text/javascript">
      $(document).ready(function() {
          $('.login-top-right-link').addClass('active-nav-link-x')
      })
  </script>
{% endblock %}

src_1 - 복사본/ui/templates/theme/register.html
{% extends 'base_x.html' %}
{% load static %}

{% block title %} Register {% endblock %}

{% block container %}
<div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <!--
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                -->
                <div class="col-lg-8 offset-lg-2">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create An Account!</h1>
                        </div>
                        <form class="user", method="POST" , action=".">
                            {% csrf_token %}
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label for="first_name">First name</label>
                                    <input type="text" class="form-control form-control-user" id="first_name" placeholder="First Name" value="Wes">
                                </div>
                                <div class="col-sm-6">
                                    <label for="last_name">Last name</label>
                                    <input type="text" class="form-control form-control-user" id="last_name" placeholder="Last Name" value="McKinney">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control form-control-user" id="email" placeholder="Email Address" value="wes@gmail.com">
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control form-control-user" id="password" placeholder="Password" value="Wes@123">
                                </div>
                                <div class="col-sm-6">
                                    <label for="conf_password">Confirm Password</label>
                                    <input type="password" class="form-control form-control-user" id="conf_password" placeholder="Repeat Password" value="Wes@123">
                                </div>
                            </div>
                            <a href="{% url 'users:login_url' %}" class="btn btn-primary btn-user btn-block">
                            Register Account
                            </a>
                            <hr>
                            <a href="{% url 'index_url' %}" class="btn btn-google btn-user btn-block">
                              <i class="fab fa-google fa-fw"></i> Register with Google
                            </a>
                            <a href="{% url 'index_url' %}" class="btn btn-facebook btn-user btn-block">
                              <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                            </a>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="{% url 'users:forgot_password_url' %}">Forgot Password?</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="{% url 'users:login_url' %}">Already have an account? Login!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_body %}
  <script type="text/javascript">
      $(document).ready(function() {
          $('.register-top-right-link').addClass('active-nav-link-x')
      })
  </script>
{% endblock %}

src_1 - 복사본/ui/templates/theme/tables.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Tables {% endblock %}


{% block css %}
<!-- Custom styles for this page -->
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}



{% block container_fluid %}

<script>

    // function send() {
    
    //     document.getElementById( 'jb' ).value = '100';
    //     setTimeout(function() {
    //     show("test 2");
    //     }, 3000);
        
    //     alert("시뮬레이션 진행 중");
    //     document.getElementById("contents").submit();
    //     }
    
    function startProgress() {
          const progressBar = document.getElementById('progressBar');
          let currentValue = 0;
          const duration = 1000; // 10초(밀리초)
    
          const interval = setInterval(() => {
            currentValue += 1;
            progressBar.value = currentValue;
    
            if (currentValue >= 100) {
              clearInterval(interval);
              triggerAlarm();
            }
          }, duration / 100);
        }
    
    function triggerAlarm() {
        // 여기에 알람을 울리는 코드를 넣으세요 (예: alert 사용)
        alert('분석 완료');
        document.getElementById("contents").submit();
    }
    

</script>

<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">사외적치블록 선정 시뮬레이터</h1>
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <form id="contents" name="contents" method="get" action="{% url 'users:tables_result_url' %}">
                            <br>
                            {% csrf_token %}
                            <p>
                            <input type="file" name="myfile" accept=".csv">
                            </p>
                            
                            <p>
                            잔여공정일 기준 : <input name="option1" type="text">
                            </p>
                            
                            <p>
                            사외적치 블록 수 기준 : <input name="option2" type="text">
                            </p>
                            
                            <p>
                            <button type="button" onclick="startProgress();">분석진행</button>
                            </p>
                            
                            <p>
                                <progress class="progress" id="progressBar" value="0" max="100" id="jb"></progress>
                            </p>
                        </form>
                    </thead>
                </table>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js_body %}
<!-- Data Tables -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock %}

src_1 - 복사본/ui/templates/theme/utilities-animation.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Utilities (Animations) {% endblock %}

{% block container_fluid %}
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-1 text-gray-800">Animation Utilities</h1>
    <p class="mb-4">Bootstrap's default utility classes can be found on the official <a href="https://getbootstrap.com/docs">Bootstrap Documentation</a> page. The custom utilities below were created to extend this theme past the default utility classes built into Bootstrap's framework.</p>
    <!-- Content Row -->
    <div class="row">
        <!-- Grow In Utility -->
        <div class="col-lg-6">
            <div class="card position-relative">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Grow In Animation Utilty</h6>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <code>.animated--grow-in</code>
                    </div>
                    <div class="small mb-1">Navbar Dropdown Example:</div>
                    <nav class="navbar navbar-expand navbar-light bg-light mb-4">
                        <a class="navbar-brand" href="#">Navbar</a>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                                </a>
                                <div class="dropdown-menu dropdown-menu-right animated--grow-in" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                    <p class="mb-0 small">Note: This utility animates the CSS transform property, meaning it will override any existing transforms on an element being animated! In this theme, the grow in animation is only being used on dropdowns within the navbar.</p>
                </div>
            </div>
        </div>
        <!-- Fade In Utility -->
        <div class="col-lg-6">
            <div class="card position-relative">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Fade In Animation Utilty</h6>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <code>.animated--fade-in</code>
                    </div>
                    <div class="small mb-1">Navbar Dropdown Example:</div>
                    <nav class="navbar navbar-expand navbar-light bg-light mb-4">
                        <a class="navbar-brand" href="#">Navbar</a>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                                </a>
                                <div class="dropdown-menu dropdown-menu-right animated--fade-in" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </nav>
                    <div class="small mb-1">Dropdown Button Example:</div>
                    <div class="dropdown mb-4">
                        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                        </button>
                        <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                    <p class="mb-0 small">Note: This utility animates the CSS opacity property, meaning it will override any existing opacity on an element being animated!</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}