src_1 - 복사본/Project/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    re_path(r'^$', views.LoginView.as_view(), name="login_url"),

    #Index
    re_path(r'^$', views.IndexView.as_view(), name="index_url"),
    
    path('users/', include('users.urls', namespace="users")),
]

src_1 - 복사본/app/urls.py
from django.urls import re_path, path , include
from . import views

app_name = "users"


urlpatterns = [
   	# Login, Register, Forgot password, Logout
    re_path(r'^index/$', views.IndexView.as_view(), name="index_url"),
    re_path(r'^login/$', views.LoginView.as_view(), name="login_url"),
    re_path(r'^register/$', views.RegisterView.as_view(), name="register_url"),
    re_path(r'^forgot-password/$', views.ForgotPasswordView.as_view(), name="forgot_password_url"),
    re_path(r'^logout/$', views.LogoutView.as_view(), name="logout_url"),

    re_path(r'^charts/$', views.ChartsView.as_view(), name="charts_url"),


    re_path(r'^tables/$', views.TablesView.as_view(), name="tables_url"),
    re_path(r'^tables_result/$', views.Tables_result_View.as_view(), name="tables_result_url"),


    re_path(r'^tables1/$', views.TablesView1.as_view(), name="tables1_url"),
    re_path(r'^tables2/$', views.TablesView2.as_view(), name="tables2_url"),
    re_path(r'^tables3/$', views.TablesView3.as_view(), name="tables3_url"),
    re_path(r'^tables4/$', views.TablesView4.as_view(), name="tables4_url"),
    re_path(r'^tables5/$', views.TablesView5.as_view(), name="tables5_url"),
    re_path(r'^tables6/$', views.TablesView6.as_view(), name="tables6_url"),
    re_path(r'^tables7/$', views.TablesView7.as_view(), name="tables7_url"),
    re_path(r'^tables8/$', views.TablesView8.as_view(), name="tables8_url"),
    
    re_path(r'^simulation_count_url/$', views.simulation_count_url.as_view(), name="simulation_count_url"),
    re_path(r'^simulation_count_results_url/$', views.simulation_count_results_url.as_view(), name="simulation_count_results_url"),

    re_path(r'^simulation_close_url/$', views.simulation_close_url.as_view(), name="simulation_close_url"),
    re_path(r'^simulation_close_results_url/$', views.simulation_close_results_url.as_view(), name="simulation_close_results_url"),

    re_path(r'^buttons/$', views.ButtonsView.as_view(), name="buttons_url"),

    re_path(r'^cards/$', views.CardsView.as_view(), name="cards_url"),

	re_path(r'^page_not_found/$', views.PageNotFoundView.as_view(), name="page_not_found_url"),    

	re_path(r'^blank/$', views.BlankView.as_view(), name="blank_page_url"),    

	# Utilities
	re_path(r'^colors/$', views.ColorsView.as_view(), name="colors_url"),    

	re_path(r'^borders/$', views.BordersView.as_view(), name="borders_url"),    

	re_path(r'^animations/$', views.AnimationsView.as_view(), name="animations_url"),    

	re_path(r'^others/$', views.OthersView.as_view(), name="others_url"),    

    # re_path(r'^map/$', views.Map_View.as_view(), name="map_view_url"),
    # re_path(r'^tables1/$', views.Map_View1.as_view(), name="map_view1_url"),
    # re_path(r'^map/$', views.Map_View2.as_view(), name="index_url"),
    
]

src_1 - 복사본/ui/templates/theme/components/charts_scripts.html
{% load static %}
<!-- Page level plugins -->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
<!-- Page level custom scripts -->
<script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'js/demo/studentpred.js' %}"></script>
<script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
<script src="{% static 'js/demo/chart-bar-demo.js' %}"></script>

src_1 - 복사본/ui/templates/theme/components/navbar.html
{% load static %}

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
    </button>
    
    <img src="{% static 'resource/logos/title.png' %}" style="max-height: 100%; width: auto;">
    
    <!-- Topbar Search -->
    <!-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form> -->
    <!-- Topbar Navbar -->
    <!-- <ul class="navbar-nav ml-auto"> -->
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <!-- <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-search fa-fw"></i>
            </a> -->
            <!-- Dropdown - Messages -->
            <!-- <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                            <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li> -->
        <!-- Nav Item - Alerts -->
        <!-- <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i> -->
                <!-- Counter - Alerts -->
                <!-- <span class="badge badge-danger badge-counter">3+</span> -->
            <!-- </a> -->
            <!-- Dropdown - Alerts -->
            <!-- <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown"> -->
                <!-- <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 12, 2019</div>
                        <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 7, 2019</div>
                        $290.29 has been deposited into your account!
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-warning">
                            <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 2, 2019</div>
                        Spending Alert: We've noticed unusually high spending for your account.
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li> -->
        <!-- Nav Item - Messages -->
        <!-- <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i> -->
                <!-- Counter - Messages -->
                <!-- <span class="badge badge-danger badge-counter">7</span> -->
            <!-- </a> -->
            <!-- Dropdown - Messages -->
            <!-- <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                        <div class="status-indicator"></div>
                    </div>
                    <div>
                        <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                        <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                        <div class="status-indicator bg-warning"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
            </div>
        </li>
        <div class="topbar-divider d-none d-sm-block"></div> -->
        <!-- Nav Item - User Information -->
        <a class="dropdown-item" href="{% url 'users:logout_url' %}" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout 
        </a>
       
    <!-- </ul> -->
</nav>

src_1 - 복사본/ui/templates/theme/components/navbar_x.html
{% load static %}




<nav class="navbar navbar-expand navbar-light bg-white1 topbar mb-4_1 static-top shadow">

    <a class="d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100" href="{% url 'users:login_url' %}">
        <img class="img-responsive" src="{% static 'resource/logos/samsung_1.png' %}" id='site-logo-x' style="width: 150px; height: auto;">
    </a>

    <!-- Topbar Navbar -->
    <!-- <ul class="navbar-nav ml-auto"> -->
        <!-- Nav Item - Alerts -->
        <!-- <li class="nav-item dropdown no-arrow mx-1 data-top-right-link login-top-right-link">
            <a class="nav-link dropdown-toggle" href="{% url 'users:login_url' %}" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Login</span> -->
                <!-- Counter - Alerts -->
                <!-- <span class="badge badge-danger badge-counter">
                    <i class="fas fa-sign-in-alt fa-fw"></i>
                </span>
            </a>
        </li> -->

        <!-- <li class="nav-item dropdown no-arrow mx-1 data-top-right-link register-top-right-link">
            <a class="nav-link dropdown-toggle" href="{% url 'users:register_url' %}" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Register</span> -->

                <!-- Counter - Alerts -->
                <!-- <span class="badge badge-danger badge-counter">
                    <i class="fas fa-user-plus fa-fw"></i>
                </span>
            </a>
        </li> -->
    <!-- </ul> -->
</nav>

src_1 - 복사본/ui/templates/theme/components/sidebar.html
{% load static %}

    <ul class="navbar-nav bg-white1 sidebar sidebar-dark accordion" id="accordionSidebar">
    
      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'users:index_url' %}">
        <img class="img-fluid transparency-grid" src="{% static 'resource/logos/samsung_1.png' %}" ondragstart="return false;" data-hj-suppress="true" data-v-1ab68894="" style="max-width: 90%; height: auto;">
        <div class="sidebar-brand-text mx-3"></div>
      </a>

      
      <!-- https://i.ibb.co/D57B2Sw/2023-11-22-093420-removebg-preview-1.png -->
      <!-- <a href="https://imgbb.com/"><img src="https://i.ibb.co/CvJCjmx/2023-11-22-093920-removebg-preview.png" alt="2023-11-22-093920-removebg-preview" border="0"></a> -->
      <!-- <a href="https://imgbb.com/"><img src="https://i.ibb.co/ypF8C2H/2023-11-22-093420-removebg-preview-2.png" alt="2023-11-22-093420-removebg-preview-2" border="0"></a> -->
      <!-- <a href="https://imgbb.com/"><img src="https://i.ibb.co/yFX4rft/2023-11-22-094626.png" alt="2023-11-22-094626" border="0"></a><br /><a target='_blank' href='https://emoticoncentral.com/category/playful'>playful emoticons</a><br /> -->
      <!-- <a href="https://ibb.co/jVY3MP4"><img src="https://i.ibb.co/N1qWjdY/1.png" alt="1" border="0"></a> -->
      <!-- <a href="https://ibb.co/5xZKxzc"><img src="https://i.ibb.co/LhKNhqp/2.png" alt="2" border="0"></a><br /><a target='_blank' href='https://emoticoncentral.com/category/rage'>rage smileys</a><br /> -->
      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <!-- <li class="nav-item active">
        <a class="nav-link" href="{% url 'users:index_url' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li> -->

      <!-- Divider -->
      <!-- <hr class="sidebar-divider"> -->

      <!-- Heading -->
      <!-- <div class="sidebar-heading">
        Interface
      </div> -->

      <!-- Nav Item - Pages Collapse Menu -->
      <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Components</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Components:</h6>
            <a class="collapse-item" href="{% url 'users:buttons_url' %}">Buttons</a>
            <a class="collapse-item" href="{% url 'users:cards_url' %}">Cards</a>
          </div>
        </div>
      </li> -->

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:index_url' %}">
          <i class="fas fa-fw fa-folder"></i>
          <span style="font-size: 75%;">대시보드</span></a>
      </li>
            
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:tables_url' %}">
          <i class="fas fa-fw fa-table"></i>
          <span style="font-size: 75%;">사외적치블록 선정 시뮬레이터</span></a>
      </li>

      <!-- <li class="nav-item">
        <a class="nav-link" href="{% url 'users:tables1_url' %}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span style="font-size: 72%;">사외반출입 선정 블록 분석 결과</span></a>
      </li> -->

      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:tables2_url' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span style="font-size: 75%;">사외적치 블록 스케줄 최적화</span></a>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-table"></i>
          <span>지역별 안전 예측</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'users:tables1_url' %}">경기, 인천</a>
            <a class="collapse-item" href="{% url 'users:tables1_url' %}">부산, 경남</a>
            <a class="collapse-item" href="{% url 'users:tables1_url' %}">전북, 충남</a>
            <a class="collapse-item" href="{% url 'users:tables1_url' %}">전남, 제주</a>
            <a class="collapse-item" href="{% url 'users:tables1_url' %}">울산</a>
            <a class="collapse-item" href="{% url 'users:tables1_url' %}">강원, 경북</a>
            <a class="collapse-item" href="{% url 'users:tables1_url' %}">서해 EEZ</a>
            <a class="collapse-item" href="{% url 'users:tables1_url' %}">남해 EEZ</a>
            <a class="collapse-item" href="{% url 'users:tables1_url' %}">동해 EEZ</a>
          </div>
        </div>
      </li> -->

      <!-- Divider -->
      <!-- <hr class="sidebar-divider"> -->

      <!-- Heading -->
      <!-- <div class="sidebar-heading"> -->
        <!-- Addons -->
      <!-- </div> -->

      <!-- Nav Item - Pages Collapse Menu -->
      <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Login Screens:</h6>
            <a class="collapse-item" href="{% url 'users:login_url' %}">Login</a>
            <a class="collapse-item" href="{% url 'users:register_url' %}">Register</a>
            <a class="collapse-item" href="{% url 'users:forgot_password_url' %}">Forgot Password</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Other Pages:</h6>
            <a class="collapse-item" href="{% url 'users:page_not_found_url' %}">404 Page</a>
            <a class="collapse-item" href="{% url 'users:blank_page_url' %}">Blank Page</a>
          </div>
        </div>
      </li> -->



      <!-- Nav Item - Charts -->
      <!-- <li class="nav-item">
        <a class="nav-link" href="{% url 'users:charts_url' %}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li> -->

      <!-- Nav Item - Tables -->

      <!-- Nav Item - Tables -->
      <!-- <li class="nav-item">
        <a class="nav-link" href="{% url 'users:tables1_url' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Students Forcast of Region</span></a>
      </li> -->
      
      <!-- Nav Item - Tables -->
      <!-- <li class="nav-item">
        <a class="nav-link" href="{% url 'users:tables2_url' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>오염수준 예측</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:simulation_count_url' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>운영시나리오별 시뮬레이션</span></a>
      </li> -->

      <!-- Nav Item - Dashboard -->
      <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>운영시나리오별 시뮬레이션</span>
        </a>
          <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <a class="collapse-item" href="{% url 'users:simulation_count_url' %}">시나리오1 시뮬레이션</a>
              <a class="collapse-item" href="{% url 'users:simulation_count_url' %}">시나리오2 시뮬레이션</a>
            </div>
          </div>
      </li> -->



      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>